import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/custom/sidebar";

// export const metadata: Metadata = {
//   title: 'About Us',
//   description: 'Learn more about our team and mission.',
// };

export const metadata: Metadata = {
  title: {
    template: '%s | Papiverse',
    default: 'Papiverse',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="bg-slate-200">
        <SidebarProvider className="bg-slate-100">
          <AppSidebar />
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}