import type { Metadata } from "next";
import "../globals.css";
import "../style.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AdminSidebar } from "@/components/custom/franchisor-sidebar";
import { AuthProvider } from "@/hooks/use-auth";
import { requireRole } from "@/lib/auth";

export const metadata: Metadata = {
  title: {
    template: '%s | Papiverse',
    default: 'Papiverse',
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await requireRole(['FRANCHISOR']);
  return (
    <AuthProvider>
      <SidebarProvider className="bg-slate-100 max-w-[2560px] mx-auto">
        <AdminSidebar />
        {children}
      </SidebarProvider>
    </AuthProvider>

  );
}