import type { Metadata } from "next";
import "../globals.css";
import "../style.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { FranchiseeSidebar } from "@/components/custom/franchisee-sidebar";
import { AuthProvider } from "@/hooks/use-auth";
import { requireRole } from "@/lib/auth";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: {
    template: '%s | Papiverse',
    default: 'Papiverse',
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await requireRole(['FRANCHISEE']);
  return (
    <AuthProvider>
      <SidebarProvider className="bg-slate-100 max-w-[2560px] mx-auto">
        <FranchiseeSidebar />
        {children}

      </SidebarProvider>
    </AuthProvider>

  );
}